version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always  # Damit der Container bei Fehlern automatisch neu startet

  spark:
    image: bitnami/spark:latest
    depends_on:
      - db
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    command: ["spark-submit", "--packages", "org.postgresql:postgresql:42.2.18", "/scripts/process_data.py"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always  # Damit der Container bei Fehlern automatisch neu startet

volumes:
  db_data:
